import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Language = "es" | "en" | "pt" | "fr" | "it" | "de";
export type Theme = "light" | "dark" | "neon" | "nature" | "ocean";

interface SettingsContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  theme: Theme;
  setTheme: (theme: Theme) => void;
  rpgMode: boolean;
  setRpgMode: (val: boolean) => void;
  notifications: boolean;
  setNotifications: (val: boolean) => void;
  unit: "km" | "mi";
  setUnit: (val: "km" | "mi") => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Settings
    "settings.title": "Configuración",
    "settings.aesthetics": "Estética de la App",
    "settings.language": "Idioma",
    "settings.gamePrefs": "Preferencias de Juego",
    "settings.rpgMode": "Modo RPG Activo",
    "settings.rpgModeDesc": "Muestra niveles, XP, cofres y stats. Apágalo para una vista más deportiva.",
    "settings.pushNotif": "Notificaciones Push",
    "settings.pushNotifDesc": "Avisos de partidos e invitaciones de clanes.",
    "settings.distance": "Unidad de Distancia",
    "settings.distanceDesc": "Para buscar eventos cercanos.",
    "settings.logout": "Cerrar Sesión",
    "themes.light": "Claro",
    "themes.dark": "Oscuro",
    "themes.neon": "Neón",
    "themes.nature": "Naturaleza",
    "themes.ocean": "Océano",
    // Navigation
    "nav.events": "Eventos",
    "nav.sports": "Deportes",
    "nav.map": "Mapa",
    "nav.friends": "Amigos",
    "nav.profile": "Perfil",
    "nav.clans": "Clanes",
    // Sports
    "sports.all": "Todos",
    "sports.futbol": "Fútbol",
    "sports.tenis": "Tenis",
    "sports.golf": "Golf",
    "sports.padel": "Pádel",
    "sports.voleibol": "Vóleibol",
    // Profile
    "profile.rpgActive": "Modo RPG Activo",
    "profile.level": "Nivel",
    "profile.xpPoints": "Puntos de Experiencia",
    "profile.achievements": "Logros Obtenidos",
    "profile.progress": "Progreso",
    "profile.stats": "Stats",
    "profile.inventory": "Cofre",
    "profile.history": "Aventuras",
    "profile.logout": "Cerrar Sesión del Héroe",
    "profile.editProfile": "Editar Perfil",
    "profile.premium": "Premium",
    "profile.basic": "Básica",
    "profile.organizer": "Organizador",
    "profile.age": "Edad",
    "profile.gender": "Género",
    "profile.location": "Ubicación",
    "profile.aboutMe": "Sobre mí",
    "profile.favSports": "Deportes Favoritos",
    "profile.closeProfile": "Cerrar Perfil",
    "profile.male": "Masculino",
    "profile.female": "Femenino",
    "profile.playerAttributes": "Atributos del Jugador",
    "profile.str": "Fuerza (STR)",
    "profile.strDesc": "Aumenta al unirte a partidos (+2 XP/partido)",
    "profile.wis": "Sabiduría (WIS)",
    "profile.wisDesc": "Aumenta al crear partidos (+5 XP/partido)",
    "profile.con": "Constitución (CON)",
    "profile.conDesc": "Aumenta con el uso diario de la app",
    "profile.cha": "Carisma (CHA)",
    "profile.chaDesc": "Calculado según tu reputación deportiva",
    "profile.profileInfo": "Información de Perfil",
    "profile.favoriteSports": "Deportes favoritos",
    "profile.campaignSummary": "Resumen de Campaña",
    "profile.campaignDesc": "Has completado **{joined} partidos** como luchador y has guiado a otros jugadores creando **{created} eventos**. Tu constancia te ha otorgado **{used} días de entrenamiento** activo.",
    "profile.classRecruit": "Recluta Novato 👟",
    "profile.classAspirant": "Aspirante Activo ⚡",
    "profile.classWarrior": "Guerrero del Fitness 🏋️‍♂️",
    "profile.classMaster": "Maestro del Match 🏆",
    "profile.classLegend": "Leyenda de Caracas 🌟",
    "profile.rarityNovice": "Novato",
    "profile.rarityCommon": "Común",
    "profile.rarityRare": "Raro",
    "profile.rarityEpic": "Épico",
    "profile.rarityLegendary": "Legendario",
    "profile.achievementsListTitle": "Lista de Logros y Trofeos",
    "profile.active": "Activos",
    "profile.adventureLog": "Registro de Aventuras (XP Log)",
    "profile.bronze": "Bronce 🥉",
    "profile.code": "Código:",
    "profile.createFreeAccount": "Crear Cuenta Gratis",
    "profile.emptyChest": "Cofre Vacío",
    "profile.emptyChestDesc": "No tienes cupones. ¡Organiza eventos (+25 XP), únete a partidos (+15 XP) o usa la app diariamente para ganar cofres sorpresa!",
    "profile.epicItem": "Objeto Épico 🟣",
    "profile.eventsPerMonth": "Eventos/mes",
    "profile.gold": "Oro 🥇",
    "profile.guestDesc": "Explora la app libremente. Crea tu cuenta para desbloquear todo.",
    "profile.guestDisclaimer": "Tu cuenta es 100% gratuita. Puedes explorar el mapa, ver eventos y canchas sin necesidad de registrarte.",
    "profile.guestTitle": "Perfil de Invitado",
    "profile.itemClaimed": "¡Objeto Canjeado! 🎉",
    "profile.itemClaimedDesc": "El beneficio de **{discount}** ha sido activado con éxito para tu próxima reserva de cancha o partido.",
    "profile.joinCommunity": "Únete a la comunidad",
    "profile.joinDesc": "Accede a todo TeamMatch gratis",
    "profile.legendaryItem": "Objeto Legendario 🟡",
    "profile.locked": "Bloqueado",
    "profile.loginExisting": "Ya tengo cuenta - Iniciar Sesión",
    "profile.magicChest": "Cofre de Objetos Mágicos",
    "profile.noXp": "Aún no has ganado experiencia. ¡Explora el mapa y únete a un partido!",
    "profile.platinum": "Platino 💎",
    "profile.players": "Jugadores",
    "profile.rating": "Rating",
    "profile.silver": "Plata 🥈",
    "profile.unlocked": "Obtenido",
    "profile.xpForNextLevel": "+{xp} XP para Nivel {level}",
    // Events
    "events.joinEvent": "Unirme al Partido",
    "events.createEvent": "Crear Evento",
    "events.noEvents": "No hay eventos disponibles",
    "events.search": "Buscar eventos...",
    "events.participants": "Participantes",
    "events.registerClan": "Inscribir mi Clan",
    "events.tab.upcoming": "Próximos",
    "events.tab.mine": "Mis Partidos",
    "events.tab.requests": "Solicitudes",
    "events.upcoming": "Próximamente",
    "events.error.noPermission": "No tienes permiso para realizar esta acción.",
    "events.error.processing": "Error al procesar la solicitud: ",
    "events.noPendingRequests": "No tienes solicitudes pendientes nuevas",
    "events.wantsToJoin": "quiere unirse a tu partido de",
    "events.viewProfile": "Ver Perfil",
    "events.noUpcomingMatches": "No tienes partidos próximos programados",
    // Friends
    "friends.title": "Amigos",
    "friends.findPlayers": "Buscar Jugadores",
    "friends.myFriends": "Mis Amigos",
    "friends.noFriends": "No hay perfiles disponibles",
    "friends.findPlayersDescription": "Vuelve más tarde o ajusta tus filtros",
    "friends.resetList": "Reiniciar",
    "friends.requests": "Solicitudes Recibidas",
    "friends.accept": "Aceptar",
    "friends.reject": "Rechazar",
    "friends.defaultName": "Deportista",
    "friends.unknownLocation": "Ubicación desconocida",
    "friends.noDescription": "Sin descripción",
    "friends.acceptedXp": "¡Aceptaste a {name} como amigo! 🤝",
    "friends.sendingRequest": "Enviando solicitud...",
    "friends.connectingWith": "Conectando con",
    "friends.requestSent": "¡SOLICITUD ENVIADA! 🤝",
    "friends.sent": "¡Enviado!",
    "friends.requestDesc": "Has enviado una solicitud de Match a {name}. Ahora debes esperar a que la apruebe para aparecer en tu lista de amigos.",
    "friends.gotIt": "¡Entendido!",
    "friends.problem": "Hubo un problema",
    "friends.errorDesc": "No pudimos enviar tu solicitud. Verifica tu conexión.",
    "friends.newMatch": "¡NUEVO MATCH! 🤝",
    "friends.requestAccepted": "¡SOLICITUD ACEPTADA!",
    "friends.nowFriends": "¡Tú y {name} ahora son amigos! Han ganado +1 punto de Carisma.",
    "friends.forYou": "Para ti",
    "friends.loadingProfiles": "Cargando perfiles reales...",
    "friends.compatible": "Compatible",
    "friends.makeMatch": "¡Hacer Match!",
    "friends.mySavedFriends": "Mis Amigos Guardados",
    "friends.friendsCount": "amigos",
    "friends.searchPlaceholder": "Buscar amigo por nombre, deporte...",
    "friends.searchEmpty": "No se encontraron amigos con ese criterio",
    "friends.noFriendsAdded": "Aún no tienes amigos agregados. ¡Busca conexiones en la pestaña 'Para ti'!",
    "friends.sendMessage": "Enviar Mensaje",
    // Clans
    "clans.title": "Clanes",
    "clans.createClan": "Crear Clan",
    "clans.joinClan": "Unirse a Clan",
    "clans.myClan": "Mi Clan",
    "clans.captain": "Capitán",
    "clans.members": "Miembros",
    "clans.search": "Buscar clanes...",
    "clans.subtitle": "Tu equipo permanente",
    "clans.noClans": "No perteneces a ningún clan",
    "clans.createFirst": "Crea tu primer clan",
    "clans.form.name": "Nombre del Clan",
    "clans.form.sport": "Deporte Principal",
    "clans.form.primaryColor": "Color Primario",
    "clans.form.secondaryColor": "Color Secundario",
    "clans.form.desc": "Descripción",
    "clans.btn.create": "Crear Clan",
    "clans.btn.creating": "Creando...",
    "clans.join.title": "Unirse a un Clan",
    "clans.join.desc": "Pídele al capitán de tu equipo el código de invitación e ingrésalo abajo.",
    "clans.btn.join": "Solicitar Unión",
    "common.add": "Agregar",
    "common.delete": "Eliminar",
    "events.error.alreadyApplied": "Ya enviaste una solicitud",
    "events.error.joinError": "Error al solicitar unirse",
    "events.error.allClanMembersEnrolled": "Todos los miembros seleccionados ya están inscritos en este evento",
    "events.error.someClanMembersEnrolled": "Algunos miembros ya están inscritos en este evento",
    "events.error.joinClanError": "Error al inscribir al clan",
    "events.error.deleteEvent": "Error al eliminar el evento",
    "events.error.onlyHostCanAccept": "Solo el creador del evento puede aceptar o rechazar solicitudes.",
    "events.success.actionComplete": "Has {action} la solicitud.",
    "events.error.updateRequest": "Error al actualizar la solicitud",
    "events.error.alreadyInMatch": "{name} ya está en el partido.",
    "events.success.addedToMatch": "¡{name} ha sido agregado al partido!",
    "events.success.requestSentTo": "¡Solicitud enviada a {name}!",
    "events.error.inviteError": "Error al invitar a {name}.",
    "events.confirmLeave": "¿Estás seguro de que deseas salirte de este partido?",
    "events.success.requestSentTitle": "¡Solicitud enviada!",
    "events.success.requestSentDesc": "Tu solicitud para unirte al partido de {sport} ha sido enviada con éxito.",
    "events.date": "Fecha",
    "events.time": "Hora",
    "events.location": "Lugar",
    "events.spots": "Cupos",
    "events.locationNotAvailable": "Ubicación no disponible",
    "events.howToGetThere": "Cómo llegar con Google Maps",
    "events.realTime": "En tiempo real",
    "events.fromYourLocation": "Desde tu ubicación",
    "events.description": "Descripción",
    "events.defaultDescription": "Partido amistoso, cancha sintética con luces. Trae ropa cómoda y agua. Se aceptan jugadores con experiencia, ambiente respetuoso y competitivo.",
    "events.pendingRequests": "Solicitudes pendientes",
    "events.approvedPlayers": "Jugadores aprobados",
    "events.inviteFriends": "Invitar Amigos",
    "events.spotsAvailable": "cupos disponibles",
    "events.loadingPlayers": "Cargando jugadores...",
    "events.applyCoupon": "Aplicar Cupón RPG:",
    "events.noCoupon": "-- Sin cupón --",
    "events.contribution": "Aporte",
    "events.free": "Gratis",
    "events.youAreHost": "Eres el organizador 👑",
    "events.deleteEvent": "Eliminar Evento",
    "events.leaveMatch": "Salir del partido 🚪",
    "events.cancelRequest": "Cancelar solicitud ✖️",
    "events.sending": "Enviando...",
    "events.eventFull": "Evento Lleno",
    "events.requestToJoin": "Solicitar unirme",
    "events.enrolling": "Inscribiendo...",
    "events.enrollClan": "Inscribir Clan",
    "events.inviteFriendsTitle": "Invitar Amigos",
    "events.loadingFriends": "Cargando amigos...",
    "events.noFriendsAvailable": "No tienes amigos disponibles para invitar o todos ya están en el partido.",
    "events.backToMatch": "Volver al Partido",
    "events.deleteEventConfirmTitle": "¿Eliminar Evento?",
    "events.deleteEventConfirmDesc": "Esta acción eliminará {title} de forma permanente. Todos los participantes serán removidos y no habrá forma de revertirlo.",
    "events.selectMembers": "Seleccionar Miembros",
    "events.selectMembersDesc": "El evento tiene {spots} cupos. Selecciona quiénes participarán.",
    "events.error.maxMembers": "Solo puedes seleccionar hasta {spots} miembros.",
    "events.join": "Unirse",
    "events.viewRoute": "Ver Ruta",
    "clans.btn.joining": "Enviando...",
    "clans.inviteCode": "Código Invitación:",
    "clans.played": "Jugados",
    "clans.won": "Ganados",
    "clans.lost": "Perdidos",
    "clans.inviteFriends": "+ Invitar Amigos",
    "clans.leaveClan": "Salir del Clan",
    "clans.editClan": "Editar Clan",
    "clans.requests": "Solicitudes de Unión",
    "clans.errorDuplicateName": "Ya existe un clan con ese nombre",
    "clans.errorCreate": "Error al crear el clan",
    "clans.errorInvalidCode": "Código inválido",
    "clans.errorAlreadyRequested": "Ya enviaste una solicitud a este clan",
    "clans.successJoinRequest": "Solicitud enviada al capitán del clan",
    "clans.errorJoin": "Error al unirse al clan",
    "clans.successFriendAdded": "Amigo añadido al clan",
    "clans.errorAlreadyMember": "Ya está en el clan",
    "clans.errorAddFriend": "Error al añadir amigo",
    "clans.successUpdated": "Clan actualizado",
    "clans.errorEdit": "Error al editar el clan",
    "clans.confirmRemoveMember": "¿Seguro que deseas eliminar a este miembro del clan?",
    "clans.errorRemoveMember": "Error al eliminar miembro",
    "clans.confirmLeave": "¿Seguro que deseas salir de este clan?",
    "clans.errorLeave": "Error al salir del clan",
    // Common
    "common.back": "Volver",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.success": "¡Éxito!",
    "common.search": "Buscar...",
    "common.noResults": "Sin resultados",
    "common.years": "años",
    "common.used": "Usado",
    "common.copied": "Copiado",
    "common.copy": "Copiar",
    "common.redeem": "Canjear",
    "common.user": "Usuario",
    // Map
    "map.distanceNear": "Cerca (≤ 5km)",
    "map.distanceMedium": "Medio (≤ 15km)",
    "map.distanceAny": "Cualquier distancia",
    "map.scheduledMatches": "Partidos programados",
    "map.coordsNotAvailable": "Coordenadas no disponibles.",
    "map.loading": "Cargando mapa...",
    "map.hub": "Hub Deportivo",
    "map.freeAccess": "Acceso gratuito",
    "map.perHour": "hora",
    "map.commentsTitle": "Comentarios de la cancha",
    "map.commentsDesc": "Mira opiniones o escribe sobre esta cancha",
    "map.noMatches": "No hay partidos programados aquí",
    "map.createOne": "¡Ve a la pestaña Eventos para crear uno!",
    "map.players": "jugadores",
    "map.myLocation": "Mi ubicación",
    "map.gpsLoc": "Mi ubicación GPS",
    "map.error.unsupported": "Tu navegador no soporta geolocalización",
    "map.error.failed": "No se pudo obtener tu ubicación",
    "map.error.denied": "Permiso de ubicación denegado",
    "map.error.unavailable": "Ubicación no disponible",
    "map.error.timeout": "Tiempo de espera agotado",
    "sports.title": "Deportes",
    "sports.football": "Fútbol",
    "sports.tennis": "Tenis",
    "sports.other": "Otro",
    "common.close": "Cerrar",
    // CreateEventForm
    "createEvent.title": "Nuevo evento",
    "createEvent.subtitle": "Completa los datos para publicar tu evento",
    "createEvent.sport": "Deporte",
    "createEvent.intensity": "Intensidad",
    "createEvent.date": "Fecha",
    "createEvent.time": "Hora",
    "createEvent.facility": "Instalación / Cancha",
    "createEvent.loadingCourts": "Cargando canchas disponibles...",
    "createEvent.noCourts": "No hay canchas registradas en la app.",
    "createEvent.registerFirst": "Registra primero una cancha en la sección de Canchas.",
    "createEvent.createCourt": "+ Crear nueva cancha",
    "createEvent.selectCourt": "-- Selecciona una cancha --",
    "createEvent.autoClan": "Inscribir Clan Automáticamente",
    "createEvent.noClan": "-- No inscribir clan completo --",
    "createEvent.enrollClan": "Inscribir a {name} ({count} miembros)",
    "createEvent.clanNote": "Si seleccionas un clan, todos sus miembros actuales serán inscritos automáticamente en este evento.",
    "createEvent.maxCapacity": "Capacidad máxima",
    "createEvent.capacityPlaceholder": "Ej: 12 jugadores (opcional)",
    "createEvent.description": "Descripción",
    "createEvent.descPlaceholder": "Ej: Traer ropa cómoda, agua y actitud deportiva. (Máximo 150 caracteres)",
    "createEvent.publishing": "Publicando evento…",
    "createEvent.publish": "Publicar evento",
    "createEvent.intensity.principiante": "Principiante",
    "createEvent.intensity.intermedio": "Intermedio",
    "createEvent.intensity.pro": "Pro",
    "createEvent.published": "¡EVENTO PUBLICADO! ⚽",
    "createEvent.done": "¡Listo!",
    "createEvent.successMsg": "Tu partido ya está en el mapa, listo para que otros jugadores se unan. ¡A jugar!",
    "createEvent.understood": "¡Entendido!",
    "createEvent.loginRequired": "Debes iniciar sesión para crear un evento.",
    "createEvent.emailError": "No se pudo obtener el email del usuario. Intenta cerrar sesión y volver a entrar.",
    "createEvent.error": "Error al crear el evento",
    "createEvent.unexpectedError": "Error inesperado al crear el evento.",
    "createEvent.err.sport": "Selecciona un deporte",
    "createEvent.err.intensity": "Selecciona la intensidad",
    "createEvent.err.date": "La fecha es obligatoria",
    "createEvent.err.time": "La hora es obligatoria",
    "createEvent.err.court": "Selecciona una cancha obligatoriamente",
    // EditProfile
    "editProfile.title": "Editar Perfil",
    "editProfile.profilePhoto": "Foto de perfil",
    "editProfile.fullName": "Nombre completo",
    "editProfile.namePlaceholder": "Tu nombre",
    "editProfile.email": "Correo electrónico",
    "editProfile.emailNote": "Al cambiar el correo electrónico, se enviará un mensaje de confirmación.",
    "editProfile.age": "Edad",
    "editProfile.gender": "Género",
    "editProfile.selectGender": "Seleccionar...",
    "editProfile.male": "Masculino",
    "editProfile.female": "Femenino",
    "editProfile.other": "Otro",
    "editProfile.location": "Ubicación (Municipio/Zona)",
    "editProfile.locationPlaceholder": "Ej. Chacao, Caracas",
    "editProfile.aboutMe": "Sobre mí (Descripción)",
    "editProfile.aboutPlaceholder": "Cuéntanos un poco sobre ti, tu nivel de juego, etc.",
    "editProfile.preferredSports": "Deportes preferidos",
    "editProfile.organizerMode": "Modo Organizador",
    "editProfile.organizerDesc": "Te permite registrar y gestionar tus propias instalaciones y canchas",
    "editProfile.saveChanges": "Guardar Cambios",
    "editProfile.success": "Perfil actualizado correctamente",
    "editProfile.error": "Error al actualizar el perfil",
    "editProfile.imgRequired": "Debes seleccionar una imagen.",
    "editProfile.imgError": "Error al subir la imagen",
    // EventCard
    "eventCard.free": "Gratis",
    "eventCard.spots": "cupos",
    "eventCard.viewEvent": "Ver evento",
    "eventCard.waitingRequest": "Esperando solicitud",
    "eventCard.joinEvent": "Unirse al evento",
    // CanchasScreen
    "canchas.title": "Canchas",
    "canchas.available": "Canchas disponibles",
    "canchas.selectForEvent": "Selecciona una cancha para tu evento",
    "canchas.addCourt": "Añadir cancha",
    "canchas.add": "Añadir",
    "canchas.noCourts": "No hay canchas por ahora",
    "canchas.beFirst": "Sé el primero en añadir una cancha",
    "canchas.addFirst": "Añadir primera cancha",
    "canchas.addTitle": "Añadir cancha",
    "canchas.addSubtitle": "Registra una nueva cancha deportiva",
    "canchas.name": "Nombre",
    "canchas.namePlaceholder": "Ej: Cancha San Bernardino",
    "canchas.nameRequired": "El nombre es obligatorio",
    "canchas.sportRequired": "Selecciona un deporte",
    "canchas.location": "Ubicación",
    "canchas.locationRequired": "Elige la ubicación en el mapa",
    "canchas.tapMap": "Toca el mapa para elegir la ubicación",
    "canchas.locationSelected": "Ubicación seleccionada",
    "canchas.description": "Descripción",
    "canchas.descPlaceholder": "Iluminación nocturna, vestuarios, estacionamiento...",
    "canchas.pricePerHour": "Precio por hora (Bs.)",
    "canchas.pricePlaceholder": "Ej: 50 (opcional)",
    "canchas.saving": "Guardando cancha…",
    "canchas.save": "Guardar cancha",
    "canchas.added": "¡Cancha añadida!",
    "canchas.addedDesc": "Ya aparece en el listado de canchas",
    "canchas.loadingMap": "Cargando mapa…",
    "canchas.searchingAddress": "Buscando dirección...",
    // CanchaComments
    "comments.title": "Comentarios",
    "comments.loading": "Cargando comentarios…",
    "comments.noComments": "Sin comentarios aún",
    "comments.beFirst": "Sé el primero en dejar un comentario sobre las condiciones o accesibilidad de esta cancha.",
    "comments.noCommentsYet": "Nadie ha comentado en esta cancha todavía.",
    "comments.player": "Jugador",
    "comments.verified": "Verificado",
    "comments.checkingAccess": "Comprobando acceso…",
    "comments.loginToComment": "Inicia sesión para comentar",
    "comments.shareOpinion": "Comparte tu opinión sobre esta cancha con la comunidad.",
    "comments.loginRegister": "Iniciar Sesión / Registrarse",
    "comments.restricted": "Acceso restringido",
    "comments.restrictedDesc": "Solo puedes comentar si has participado o estás participando en un evento en esta cancha. ¡Únete a un partido o crea uno aquí primero!",
    "comments.placeholder": "Escribe tu opinión sobre la cancha (iluminación, estado, etc.)…",
    "comments.readyToComment": "Listo para comentar",
    "comments.submitError": "Error al enviar el comentario.",
    // Auth
    "auth.welcomeBack": "Bienvenido",
    "auth.welcomeBackEmoji": "de vuelta 👋",
    "auth.createAccount": "Crea tu cuenta",
    "auth.createAccountEmoji": "y entra a jugar ⚡",
    "auth.loginSubtitle": "Inicia sesión para ver y unirte a eventos.",
    "auth.registerSubtitle": "Regístrate gratis. En segundos estás dentro.",
    "auth.fullName": "Nombre completo",
    "auth.namePlaceholder": "Ej: Diego Ramírez",
    "auth.registerAsOrganizer": "Quiero registrarme como Organizador",
    "auth.email": "Correo electrónico",
    "auth.password": "Contraseña",
    "auth.minChars": "Mín. 6 caracteres",
    "auth.yourPassword": "Tu contraseña",
    "auth.forgotPassword": "¿Olvidaste tu contraseña?",
    "auth.loggingIn": "Iniciando sesión...",
    "auth.creatingAccount": "Creando cuenta...",
    "auth.loggedIn": "¡Sesión iniciada!",
    "auth.accountCreated": "¡Cuenta creada!",
    "auth.login": "Iniciar sesión",
    "auth.createFree": "Crear cuenta gratis",
    "auth.or": "o",
    "auth.noAccount": "¿No tienes cuenta? Regístrate",
    "auth.hasAccount": "¿Ya tienes cuenta? Inicia sesión",
    "auth.terms": "Al continuar aceptas los Términos de Uso y la Política de Privacidad de TeamMatch.",
    "auth.loggedInMsg": "¡Sesión iniciada! Entrando...",
    "auth.accountCreatedMsg": "¡Cuenta creada! Bienvenido...",
    "auth.fillFields": "Completa todos los campos obligatorios.",
    "auth.enterName": "Ingresa tu nombre para continuar.",
    "auth.minPassword": "La contraseña debe tener al menos 6 caracteres.",
    "auth.err.invalidLogin": "Correo o contraseña incorrectos. Revisa tus datos.",
    "auth.err.emailNotConfirmed": "Confirma tu correo antes de iniciar sesión.",
    "auth.err.alreadyRegistered": "Ya existe una cuenta con ese correo. Intenta iniciar sesión.",
    "auth.err.weakPassword": "La contraseña debe tener al menos 6 caracteres.",
    "auth.err.invalidEmail": "Ingresa un correo electrónico válido.",
    "auth.err.rateLimit": "Demasiados intentos. Espera unos minutos e intenta de nuevo.",
    // MySports
    "mySports.title": "Mis deportes",
    "mySports.subtitle": "Tus estadísticas y partidos por disciplina",
    "mySports.match": "partido",
    "mySports.matches": "partidos",
    "mySports.noSports": "No te has unido a eventos de ningún deporte todavía",
    // CouponPopup
    "coupon.specialAd": "Anuncio Especial 📣",
    "coupon.copied": "¡Copiado!",
    "coupon.copyHint": "*Haz clic en el código para copiarlo al portapapeles.",
    // Welcome
    "welcome.availableIn": "Disponible en Caracas",
    "welcome.nextMatch": "Tu próximo",
    "welcome.awaits": "partido te espera.",
    "welcome.subtitle": "Encuentra eventos deportivos cerca de ti, únete con un toque o crea el tuyo y arma equipo.",
    "welcome.liveMap": "Mapa en vivo",
    "welcome.liveMapDesc": "Eventos cerca en tiempo real",
    "welcome.joinEasy": "Únete fácil",
    "welcome.joinEasyDesc": "Solicita un cupo en segundos",
    "welcome.byLevel": "Por nivel",
    "welcome.byLevelDesc": "Juega con gente a tu altura",
    "welcome.startPlaying": "Empezar a jugar",
    "welcome.hasAccount": "Ya tengo cuenta",
    "welcome.terms": "Al continuar aceptas los Términos y la Política de Privacidad",
    // LoginPrompt
    "loginPrompt.joinTo": "¡Únete para {action}!",
    "loginPrompt.defaultAction": "realizar esta acción",
    "loginPrompt.subtitle": "Crea tu cuenta gratis y accede a todos los partidos y canchas de Caracas.",
    "loginPrompt.perk1": "Únete a partidos cerca de ti",
    "loginPrompt.perk2": "Crea eventos y arma tu equipo",
    "loginPrompt.perk3": "Gana XP y desbloquea recompensas",
    "loginPrompt.perk4": "Matchmaking por nivel y deporte",
    "loginPrompt.createFree": "Crear Cuenta Gratis",
    "loginPrompt.hasAccount": "Ya tengo cuenta — Iniciar Sesión",
    "loginPrompt.notNow": "Ahora no, seguir explorando",
  },
  en: {
    "settings.title": "Settings",
    "settings.aesthetics": "App Aesthetics",
    "settings.language": "Language",
    "settings.gamePrefs": "Game Preferences",
    "settings.rpgMode": "RPG Mode Active",
    "settings.rpgModeDesc": "Shows levels, XP, chests and stats. Turn off for a cleaner sports view.",
    "settings.pushNotif": "Push Notifications",
    "settings.pushNotifDesc": "Match alerts and clan invitations.",
    "settings.distance": "Distance Unit",
    "settings.distanceDesc": "For finding nearby events.",
    "settings.logout": "Log Out",
    "themes.light": "Light",
    "themes.dark": "Dark",
    "themes.neon": "Neon",
    "themes.nature": "Nature",
    "themes.ocean": "Ocean",
    "nav.events": "Events",
    "nav.sports": "Sports",
    "nav.map": "Map",
    "nav.friends": "Friends",
    "nav.profile": "Profile",
    "nav.clans": "Clans",
    "profile.rpgActive": "RPG Mode Active",
    "profile.level": "Level",
    "profile.xpPoints": "Experience Points",
    "profile.achievements": "Achievements",
    "profile.progress": "Progress",
    "profile.stats": "Stats",
    "profile.inventory": "Chest",
    "profile.history": "History",
    "profile.logout": "Logout",
    "profile.editProfile": "Edit Profile",
    "profile.premium": "Premium",
    "profile.basic": "Basic",
    "profile.organizer": "Organizer",
    "profile.age": "Age",
    "profile.gender": "Gender",
    "profile.location": "Location",
    "profile.aboutMe": "About me",
    "profile.favSports": "Favorite Sports",
    "profile.closeProfile": "Close Profile",
    "profile.male": "Male",
    "profile.female": "Female",
    "profile.playerAttributes": "Player Attributes",
    "profile.str": "Strength (STR)",
    "profile.strDesc": "Increases when joining matches (+2 XP/match)",
    "profile.wis": "Wisdom (WIS)",
    "profile.wisDesc": "Increases when creating matches (+5 XP/match)",
    "profile.con": "Constitution (CON)",
    "profile.conDesc": "Increases with daily app use",
    "profile.cha": "Charisma (CHA)",
    "profile.chaDesc": "Calculated based on sports reputation",
    "profile.profileInfo": "Profile Info",
    "profile.favoriteSports": "Favorite Sports",
    "profile.campaignSummary": "Campaign Summary",
    "profile.campaignDesc": "You have completed **{joined} matches** as a fighter and guided other players by creating **{created} events**. Your consistency has granted you **{used} days of active training**.",
    "profile.classRecruit": "Rookie Recruit 👟",
    "profile.classAspirant": "Active Aspirant ⚡",
    "profile.classWarrior": "Fitness Warrior 🏋️‍♂️",
    "profile.classMaster": "Match Master 🏆",
    "profile.classLegend": "Caracas Legend 🌟",
    "profile.rarityNovice": "Novice",
    "profile.rarityCommon": "Common",
    "profile.rarityRare": "Rare",
    "profile.rarityEpic": "Epic",
    "profile.rarityLegendary": "Legendary",
    "profile.achievementsListTitle": "Achievements and Trophies",
    "profile.active": "Active",
    "profile.adventureLog": "Adventure Log (XP Log)",
    "profile.bronze": "Bronze 🥉",
    "profile.code": "Code:",
    "profile.createFreeAccount": "Create Free Account",
    "profile.emptyChest": "Empty Chest",
    "profile.emptyChestDesc": "You have no coupons. Organize events (+25 XP), join matches (+15 XP) or use the app daily to earn surprise chests!",
    "profile.epicItem": "Epic Item 🟣",
    "profile.eventsPerMonth": "Events/month",
    "profile.gold": "Gold 🥇",
    "profile.guestDesc": "Explore the app freely. Create your account to unlock everything.",
    "profile.guestDisclaimer": "Your account is 100% free. You can explore the map, see events and courts without registering.",
    "profile.guestTitle": "Guest Profile",
    "profile.itemClaimed": "Item Claimed! 🎉",
    "profile.itemClaimedDesc": "The **{discount}** benefit has been successfully activated for your next court or match reservation.",
    "profile.joinCommunity": "Join the community",
    "profile.joinDesc": "Access all TeamMatch for free",
    "profile.legendaryItem": "Legendary Item 🟡",
    "profile.locked": "Locked",
    "profile.loginExisting": "I already have an account - Log In",
    "profile.magicChest": "Magic Item Chest",
    "profile.noXp": "You haven't earned any experience yet. Explore the map and join a match!",
    "profile.platinum": "Platinum 💎",
    "profile.players": "Players",
    "profile.rating": "Rating",
    "profile.silver": "Silver 🥈",
    "profile.unlocked": "Unlocked",
    "profile.xpForNextLevel": "+{xp} XP for Level {level}",
    "events.joinEvent": "Join Match",
    "events.createEvent": "Create Event",
    "events.noEvents": "No events available",
    "events.search": "Search events...",
    "events.participants": "Participants",
    "events.registerClan": "Register my Clan",
    "events.tab.upcoming": "Upcoming",
    "events.tab.mine": "My Matches",
    "events.tab.requests": "Requests",
    "events.upcoming": "Upcoming",
    "events.error.noPermission": "You do not have permission to do this.",
    "events.error.processing": "Error processing request: ",
    "events.noPendingRequests": "No new pending requests",
    "events.wantsToJoin": "wants to join your match of",
    "events.viewProfile": "View Profile",
    "events.noUpcomingMatches": "You have no upcoming matches scheduled",
    "events.error.alreadyApplied": "You already sent a request",
    "events.error.joinError": "Error requesting to join",
    "events.error.allClanMembersEnrolled": "All selected members are already enrolled in this event",
    "events.error.someClanMembersEnrolled": "Some members are already enrolled in this event",
    "events.error.joinClanError": "Error enrolling the clan",
    "events.error.deleteEvent": "Error deleting the event",
    "events.error.onlyHostCanAccept": "Only the event creator can accept or reject requests.",
    "events.success.actionComplete": "You have {action} the request.",
    "events.error.updateRequest": "Error updating the request",
    "events.error.alreadyInMatch": "{name} is already in the match.",
    "events.success.addedToMatch": "¡{name} has been added to the match!",
    "events.success.requestSentTo": "¡Request sent to {name}!",
    "events.error.inviteError": "Error inviting {name}.",
    "events.confirmLeave": "Are you sure you want to leave this match?",
    "events.success.requestSentTitle": "¡Request sent!",
    "events.success.requestSentDesc": "Your request to join the {sport} match has been sent successfully.",
    "events.date": "Date",
    "events.time": "Time",
    "events.location": "Location",
    "events.spots": "Spots",
    "events.locationNotAvailable": "Location not available",
    "events.howToGetThere": "How to get there with Google Maps",
    "events.realTime": "In real time",
    "events.fromYourLocation": "From your location",
    "events.description": "Description",
    "events.defaultDescription": "Friendly match, synthetic court with lights. Bring comfortable clothes and water. Players with experience accepted, respectful and competitive environment.",
    "events.pendingRequests": "Pending requests",
    "events.approvedPlayers": "Approved players",
    "events.inviteFriends": "Invite Friends",
    "events.spotsAvailable": "spots available",
    "events.loadingPlayers": "Loading players...",
    "events.applyCoupon": "Apply RPG Coupon:",
    "events.noCoupon": "-- No coupon --",
    "events.contribution": "Contribution",
    "events.free": "Free",
    "events.youAreHost": "You are the organizer 👑",
    "events.deleteEvent": "Delete Event",
    "events.leaveMatch": "Leave match 🚪",
    "events.cancelRequest": "Cancel request ✖️",
    "events.sending": "Sending...",
    "events.eventFull": "Event Full",
    "events.requestToJoin": "Request to join",
    "events.enrolling": "Enrolling...",
    "events.enrollClan": "Enroll Clan",
    "events.inviteFriendsTitle": "Invite Friends",
    "events.loadingFriends": "Loading friends...",
    "events.noFriendsAvailable": "You have no friends available to invite or everyone is already in the match.",
    "events.backToMatch": "Back to Match",
    "events.deleteEventConfirmTitle": "Delete Event?",
    "events.deleteEventConfirmDesc": "This action will permanently delete {title}. All participants will be removed and there will be no way to revert it.",
    "events.selectMembers": "Select Members",
    "events.selectMembersDesc": "The event has {spots} spots. Select who will participate.",
    "events.error.maxMembers": "You can only select up to {spots} members.",
    "events.join": "Join",
    "events.viewRoute": "View Route",
    "clans.title": "Clans",
    "clans.createClan": "Create Clan",
    "clans.joinClan": "Join Clan",
    "clans.myClan": "My Clan",
    "clans.captain": "Captain",
    "clans.members": "Members",
    "clans.search": "Search clans...",
    "clans.subtitle": "Your permanent team",
    "clans.noClans": "You do not belong to any clan",
    "clans.createFirst": "Create your first clan",
    "clans.form.name": "Clan Name",
    "clans.form.sport": "Main Sport",
    "clans.form.primaryColor": "Primary Color",
    "clans.form.secondaryColor": "Secondary Color",
    "clans.form.desc": "Description",
    "clans.btn.create": "Create Clan",
    "clans.btn.creating": "Creating...",
    "clans.join.title": "Join a Clan",
    "clans.join.desc": "Ask your team captain for the invite code and enter it below.",
    "clans.btn.join": "Request to Join",
    "clans.btn.joining": "Sending...",
    "clans.inviteCode": "Invite Code:",
    "clans.played": "Played",
    "clans.won": "Won",
    "clans.lost": "Lost",
    "clans.inviteFriends": "+ Invite Friends",
    "clans.leaveClan": "Leave Clan",
    "clans.editClan": "Edit Clan",
    "clans.requests": "Join Requests",
    "clans.errorDuplicateName": "A clan with that name already exists",
    "clans.errorCreate": "Error creating clan",
    "clans.errorInvalidCode": "Invalid code",
    "clans.errorAlreadyRequested": "You already sent a request to this clan",
    "clans.successJoinRequest": "Request sent to the clan captain",
    "clans.errorJoin": "Error joining clan",
    "clans.successFriendAdded": "Friend added to the clan",
    "clans.errorAlreadyMember": "Already a member of this clan",
    "clans.errorAddFriend": "Error adding friend",
    "clans.successUpdated": "Clan updated",
    "clans.errorEdit": "Error editing clan",
    "clans.confirmRemoveMember": "Are you sure you want to remove this member from the clan?",
    "clans.errorRemoveMember": "Error removing member",
    "clans.confirmLeave": "Are you sure you want to leave this clan?",
    "clans.errorLeave": "Error leaving clan",
    "clans.noClansAvailable": "No clans available",
    "friends.title": "Friends",
    "friends.findPlayers": "Find Players",
    "friends.myFriends": "My Friends",
    "friends.noFriends": "No profiles available",
    "friends.findPlayersDescription": "Come back later or adjust your filters",
    "friends.resetList": "Reset",
    "friends.requests": "Received Requests",
    "friends.accept": "Accept",
    "friends.reject": "Reject",
    "friends.defaultName": "Athlete",
    "friends.unknownLocation": "Unknown location",
    "friends.noDescription": "No description",
    "friends.acceptedXp": "You accepted {name} as a friend! 🤝",
    "friends.sendingRequest": "Sending request...",
    "friends.connectingWith": "Connecting with",
    "friends.requestSent": "REQUEST SENT! 🤝",
    "friends.sent": "Sent!",
    "friends.requestDesc": "You have sent a match request to {name}. Wait for them to approve to see them in your friends list.",
    "friends.gotIt": "Got it!",
    "friends.problem": "There was a problem",
    "friends.errorDesc": "We couldn't send your request. Check your connection.",
    "friends.newMatch": "NEW MATCH! 🤝",
    "friends.requestAccepted": "REQUEST ACCEPTED!",
    "friends.nowFriends": "You and {name} are now friends! You earned +1 Charisma point.",
    "friends.forYou": "For you",
    "friends.loadingProfiles": "Loading real profiles...",
    "friends.compatible": "Compatible",
    "friends.makeMatch": "Make Match!",
    "friends.mySavedFriends": "My Saved Friends",
    "friends.friendsCount": "friends",
    "friends.searchPlaceholder": "Search friend by name, sport...",
    "friends.searchEmpty": "No friends found with that criteria",
    "friends.noFriendsAdded": "You have no friends added yet. Look for connections in the 'For you' tab!",
    "friends.sendMessage": "Send Message",
    "sports.search": "Search sports...",
    "sports.title": "Sports",
    "sports.all": "All",
    "sports.futbol": "Football",
    "sports.tenis": "Tennis",
    "sports.golf": "Golf",
    "sports.padel": "Padel",
    "sports.other": "Other",
    "sports.voleibol": "Volleyball",
    "common.back": "Back",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success!",
    "common.search": "Search...",
    "common.noResults": "No results",
    "common.years": "years",
    "common.used": "Used",
    "common.copied": "Copied",
    "common.copy": "Copy",
    "common.redeem": "Redeem",
    "common.add": "Add",
    "common.delete": "Delete",
    "common.close": "Close",
    "common.user": "User",
    // CreateEventForm
    "createEvent.title": "New event",
    "createEvent.subtitle": "Fill in the details to publish your event",
    "createEvent.sport": "Sport",
    "createEvent.intensity": "Intensity",
    "createEvent.date": "Date",
    "createEvent.time": "Time",
    "createEvent.facility": "Facility / Court",
    "createEvent.loadingCourts": "Loading available courts...",
    "createEvent.noCourts": "No courts registered in the app.",
    "createEvent.registerFirst": "Register a court first in the Courts section.",
    "createEvent.createCourt": "+ Create new court",
    "createEvent.selectCourt": "-- Select a court --",
    "createEvent.autoClan": "Auto-enroll Clan",
    "createEvent.noClan": "-- Don't enroll full clan --",
    "createEvent.enrollClan": "Enroll {name} ({count} members)",
    "createEvent.clanNote": "If you select a clan, all current members will be automatically enrolled in this event.",
    "createEvent.maxCapacity": "Max capacity",
    "createEvent.capacityPlaceholder": "E.g.: 12 players (optional)",
    "createEvent.description": "Description",
    "createEvent.descPlaceholder": "E.g.: Bring comfortable clothes, water and a positive attitude. (Max 150 chars)",
    "createEvent.publishing": "Publishing event…",
    "createEvent.publish": "Publish event",
    "createEvent.intensity.principiante": "Beginner",
    "createEvent.intensity.intermedio": "Intermediate",
    "createEvent.intensity.pro": "Pro",
    "createEvent.published": "EVENT PUBLISHED! ⚽",
    "createEvent.done": "Done!",
    "createEvent.successMsg": "Your match is on the map, ready for other players to join. Let's play!",
    "createEvent.understood": "Got it!",
    "createEvent.loginRequired": "You must log in to create an event.",
    "createEvent.emailError": "Could not get user email. Try logging out and back in.",
    "createEvent.error": "Error creating event",
    "createEvent.unexpectedError": "Unexpected error creating event.",
    "createEvent.err.sport": "Select a sport",
    "createEvent.err.intensity": "Select the intensity",
    "createEvent.err.date": "Date is required",
    "createEvent.err.time": "Time is required",
    "createEvent.err.court": "You must select a court",
    // EditProfile
    "editProfile.title": "Edit Profile",
    "editProfile.profilePhoto": "Profile photo",
    "editProfile.fullName": "Full name",
    "editProfile.namePlaceholder": "Your name",
    "editProfile.email": "Email address",
    "editProfile.emailNote": "Changing your email will send a confirmation message.",
    "editProfile.age": "Age",
    "editProfile.gender": "Gender",
    "editProfile.selectGender": "Select...",
    "editProfile.male": "Male",
    "editProfile.female": "Female",
    "editProfile.other": "Other",
    "editProfile.location": "Location (City/Area)",
    "editProfile.locationPlaceholder": "E.g. Chacao, Caracas",
    "editProfile.aboutMe": "About me (Description)",
    "editProfile.aboutPlaceholder": "Tell us a bit about yourself, your skill level, etc.",
    "editProfile.preferredSports": "Preferred sports",
    "editProfile.organizerMode": "Organizer Mode",
    "editProfile.organizerDesc": "Allows you to register and manage your own facilities and courts",
    "editProfile.saveChanges": "Save Changes",
    "editProfile.success": "Profile updated successfully",
    "editProfile.error": "Error updating profile",
    "editProfile.imgRequired": "You must select an image.",
    "editProfile.imgError": "Error uploading image",
    // EventCard
    "eventCard.free": "Free",
    "eventCard.spots": "spots",
    "eventCard.viewEvent": "View event",
    "eventCard.waitingRequest": "Waiting for approval",
    "eventCard.joinEvent": "Join event",
    // CanchasScreen
    "canchas.title": "Courts",
    "canchas.available": "Available courts",
    "canchas.selectForEvent": "Select a court for your event",
    "canchas.addCourt": "Add court",
    "canchas.add": "Add",
    "canchas.noCourts": "No courts yet",
    "canchas.beFirst": "Be the first to add a court",
    "canchas.addFirst": "Add first court",
    "canchas.addTitle": "Add court",
    "canchas.addSubtitle": "Register a new sports court",
    "canchas.name": "Name",
    "canchas.namePlaceholder": "E.g.: San Bernardino Court",
    "canchas.nameRequired": "Name is required",
    "canchas.sportRequired": "Select a sport",
    "canchas.location": "Location",
    "canchas.locationRequired": "Choose a location on the map",
    "canchas.tapMap": "Tap the map to choose a location",
    "canchas.locationSelected": "Location selected",
    "canchas.description": "Description",
    "canchas.descPlaceholder": "Night lighting, locker rooms, parking...",
    "canchas.pricePerHour": "Price per hour (Bs.)",
    "canchas.pricePlaceholder": "E.g.: 50 (optional)",
    "canchas.saving": "Saving court…",
    "canchas.save": "Save court",
    "canchas.added": "Court added!",
    "canchas.addedDesc": "It now appears in the courts list",
    "canchas.loadingMap": "Loading map…",
    "canchas.searchingAddress": "Searching address...",
    // CanchaComments
    "comments.title": "Comments",
    "comments.loading": "Loading comments…",
    "comments.noComments": "No comments yet",
    "comments.beFirst": "Be the first to leave a comment about the conditions or accessibility of this court.",
    "comments.noCommentsYet": "Nobody has commented on this court yet.",
    "comments.player": "Player",
    "comments.verified": "Verified",
    "comments.checkingAccess": "Checking access…",
    "comments.loginToComment": "Log in to comment",
    "comments.shareOpinion": "Share your opinion about this court with the community.",
    "comments.loginRegister": "Log In / Register",
    "comments.restricted": "Restricted access",
    "comments.restrictedDesc": "You can only comment if you have participated or are participating in an event at this court. Join a match or create one here first!",
    "comments.placeholder": "Write your opinion about the court (lighting, condition, etc.)…",
    "comments.readyToComment": "Ready to comment",
    "comments.submitError": "Error sending comment.",
    // Auth
    "auth.welcomeBack": "Welcome",
    "auth.welcomeBackEmoji": "back 👋",
    "auth.createAccount": "Create your account",
    "auth.createAccountEmoji": "and start playing ⚡",
    "auth.loginSubtitle": "Log in to see and join events.",
    "auth.registerSubtitle": "Sign up for free. You'll be in within seconds.",
    "auth.fullName": "Full name",
    "auth.namePlaceholder": "E.g.: Diego Ramírez",
    "auth.registerAsOrganizer": "I want to register as an Organizer",
    "auth.email": "Email address",
    "auth.password": "Password",
    "auth.minChars": "Min. 6 characters",
    "auth.yourPassword": "Your password",
    "auth.forgotPassword": "Forgot your password?",
    "auth.loggingIn": "Logging in...",
    "auth.creatingAccount": "Creating account...",
    "auth.loggedIn": "Logged in!",
    "auth.accountCreated": "Account created!",
    "auth.login": "Log in",
    "auth.createFree": "Create free account",
    "auth.or": "or",
    "auth.noAccount": "Don't have an account? Sign up",
    "auth.hasAccount": "Already have an account? Log in",
    "auth.terms": "By continuing you accept TeamMatch's Terms of Use and Privacy Policy.",
    "auth.loggedInMsg": "Logged in! Entering...",
    "auth.accountCreatedMsg": "Account created! Welcome...",
    "auth.fillFields": "Please fill in all required fields.",
    "auth.enterName": "Enter your name to continue.",
    "auth.minPassword": "Password must be at least 6 characters.",
    "auth.err.invalidLogin": "Incorrect email or password. Check your info.",
    "auth.err.emailNotConfirmed": "Confirm your email before logging in.",
    "auth.err.alreadyRegistered": "An account with that email already exists. Try logging in.",
    "auth.err.weakPassword": "Password must be at least 6 characters.",
    "auth.err.invalidEmail": "Enter a valid email address.",
    "auth.err.rateLimit": "Too many attempts. Wait a few minutes and try again.",
    // MySports
    "mySports.title": "My sports",
    "mySports.subtitle": "Your stats and matches by sport",
    "mySports.match": "match",
    "mySports.matches": "matches",
    "mySports.noSports": "You haven't joined events for any sport yet",
    // CouponPopup
    "coupon.specialAd": "Special Announcement 📣",
    "coupon.copied": "Copied!",
    "coupon.copyHint": "*Click the code to copy it to the clipboard.",
    // Welcome
    "welcome.availableIn": "Available in Caracas",
    "welcome.nextMatch": "Your next",
    "welcome.awaits": "match awaits.",
    "welcome.subtitle": "Find sports events near you, join with a tap or create your own and build a team.",
    "welcome.liveMap": "Live map",
    "welcome.liveMapDesc": "Nearby events in real time",
    "welcome.joinEasy": "Join easily",
    "welcome.joinEasyDesc": "Request a spot in seconds",
    "welcome.byLevel": "By level",
    "welcome.byLevelDesc": "Play with people at your level",
    "welcome.startPlaying": "Start playing",
    "welcome.hasAccount": "I already have an account",
    "welcome.terms": "By continuing you accept the Terms and Privacy Policy",
    // LoginPrompt
    "loginPrompt.joinTo": "Join to {action}!",
    "loginPrompt.defaultAction": "perform this action",
    "loginPrompt.subtitle": "Create your free account and access all matches and courts in Caracas.",
    "loginPrompt.perk1": "Join matches near you",
    "loginPrompt.perk2": "Create events and build your team",
    "loginPrompt.perk3": "Earn XP and unlock rewards",
    "loginPrompt.perk4": "Matchmaking by level and sport",
    "loginPrompt.createFree": "Create Free Account",
    "loginPrompt.hasAccount": "I already have an account — Log In",
    "loginPrompt.notNow": "Not now, keep exploring",
    "map.distanceNear": "Near (≤ 5km)",
    "map.distanceMedium": "Medium (≤ 15km)",
    "map.distanceAny": "Any distance",
    "map.scheduledMatches": "Scheduled matches",
    "map.coordsNotAvailable": "Coordinates not available.",
    "map.loading": "Loading map...",
    "map.hub": "Sports Hub",
    "map.freeAccess": "Free access",
    "map.perHour": "hour",
    "map.commentsTitle": "Court comments",
    "map.commentsDesc": "Read reviews or write about this court",
    "map.noMatches": "No matches scheduled here",
    "map.createOne": "Go to Events tab to create one!",
    "map.players": "players",
    "map.myLocation": "My location",
    "map.gpsLoc": "My GPS location",
    "map.error.unsupported": "Your browser does not support geolocation",
    "map.error.failed": "Could not get your location",
    "map.error.denied": "Location permission denied",
    "map.error.unavailable": "Location not available",
    "map.error.timeout": "Timeout reached",
  },
  pt: {
    "settings.title": "Configurações",
    "settings.aesthetics": "Estética do App",
    "settings.language": "Idioma",
    "settings.gamePrefs": "Preferências de Jogo",
    "settings.rpgMode": "Modo RPG Ativo",
    "settings.rpgModeDesc": "Mostra níveis, XP, baús e atributos. Desligue para visão esportiva.",
    "settings.pushNotif": "Notificações Push",
    "settings.pushNotifDesc": "Avisos de partidas e convites de clãs.",
    "settings.distance": "Unidade de Distância",
    "settings.distanceDesc": "Para buscar eventos próximos.",
    "settings.logout": "Sair",
    "themes.light": "Claro",
    "themes.dark": "Escuro",
    "themes.neon": "Neon",
    "themes.nature": "Natureza",
    "themes.ocean": "Oceano",
    "nav.events": "Eventos",
    "nav.sports": "Esportes",
    "nav.map": "Mapa",
    "nav.friends": "Amigos",
    "nav.profile": "Perfil",
    "nav.clans": "Clãs",
    "profile.rpgActive": "Modo RPG Ativo",
    "profile.level": "Nível",
    "profile.xpPoints": "Pontos de Experiência",
    "profile.achievements": "Conquistas",
    "profile.progress": "Progresso",
    "profile.stats": "Stats",
    "profile.inventory": "Baú",
    "profile.history": "Histórico",
    "profile.logout": "Sair",
    "profile.editProfile": "Editar Perfil",
    "profile.organizer": "Organizador",
    "profile.age": "Idade",
    "profile.gender": "Gênero",
    "profile.location": "Localização",
    "profile.aboutMe": "Sobre mim",
    "profile.favSports": "Esportes Favoritos",
    "profile.closeProfile": "Fechar Perfil",
    "profile.male": "Masculino",
    "profile.female": "Feminino",
    "profile.playerAttributes": "Atributos do Jogador",
    "profile.str": "Força (STR)",
    "profile.strDesc": "Aumenta ao entrar em partidas (+2 XP/partida)",
    "profile.wis": "Sabedoria (WIS)",
    "profile.wisDesc": "Aumenta ao criar partidas (+5 XP/partida)",
    "profile.con": "Constituição (CON)",
    "profile.conDesc": "Aumenta com o uso diário",
    "profile.cha": "Carisma (CHA)",
    "profile.chaDesc": "Calculado pela reputação",
    "profile.profileInfo": "Informações do Perfil",
    "profile.favoriteSports": "Esportes favoritos",
    "profile.campaignSummary": "Resumo da Campanha",
    "profile.campaignDesc": "Você completou **{joined} partidas** e criou **{created} eventos**. Sua constância lhe rendeu **{used} dias de treino**.",
    "profile.classRecruit": "Recruta Novato 👟",
    "profile.classAspirant": "Aspirante Ativo ⚡",
    "profile.classWarrior": "Guerreiro Fitness 🏋️‍♂️",
    "profile.classMaster": "Mestre da Partida 🏆",
    "profile.classLegend": "Lenda de Caracas 🌟",
    "profile.rarityNovice": "Novato",
    "profile.rarityCommon": "Comum",
    "profile.rarityRare": "Raro",
    "profile.rarityEpic": "Épico",
    "profile.rarityLegendary": "Lendário",
    "profile.achievementsListTitle": "Lista de Conquistas",
    "profile.active": "Ativos",
    "profile.adventureLog": "Diário de Aventuras (XP Log)",
    "profile.bronze": "Bronze 🥉",
    "profile.code": "Código:",
    "profile.createFreeAccount": "Criar Conta Grátis",
    "profile.emptyChest": "Baú Vazio",
    "profile.emptyChestDesc": "Você não tem cupons. Organize eventos (+25 XP) ou participe de partidas (+15 XP) para ganhar baús!",
    "profile.epicItem": "Item Épico 🟣",
    "profile.eventsPerMonth": "Eventos/mês",
    "profile.gold": "Ouro 🥇",
    "profile.guestDesc": "Explore livremente. Crie uma conta para desbloquear tudo.",
    "profile.guestDisclaimer": "Sua conta é 100% grátis.",
    "profile.guestTitle": "Perfil de Visitante",
    "profile.itemClaimed": "Item Resgatado! 🎉",
    "profile.itemClaimedDesc": "O benefício **{discount}** foi ativado.",
    "profile.joinCommunity": "Junte-se à comunidade",
    "profile.joinDesc": "Acesse tudo grátis",
    "profile.legendaryItem": "Item Lendário 🟡",
    "profile.locked": "Bloqueado",
    "profile.loginExisting": "Já tenho conta - Entrar",
    "profile.magicChest": "Baú Mágico",
    "profile.noXp": "Sem experiência ainda.",
    "profile.platinum": "Platina 💎",
    "profile.players": "Jogadores",
    "profile.rating": "Avaliação",
    "profile.silver": "Prata 🥈",
    "profile.unlocked": "Desbloqueado",
    "profile.xpForNextLevel": "+{xp} XP para Nível {level}",
    "canchas.location": "Localização",
    "canchas.locationSelected": "Localização selecionada",
    "createEvent.intensity.principiante": "Iniciante",
    "createEvent.intensity.intermedio": "Intermediário",
    "createEvent.intensity.pro": "Pró",
    "events.joinEvent": "Entrar na Partida",
    "events.createEvent": "Criar Evento",
    "events.noEvents": "Nenhum evento disponível",
    "events.search": "Buscar eventos...",
    "events.participants": "Participantes",
    "events.registerClan": "Inscrever meu Clã",
    "events.tab.upcoming": "Próximos",
    "events.tab.mine": "Minhas Partidas",
    "events.tab.requests": "Solicitações",
    "clans.title": "Clãs",
    "clans.createClan": "Criar Clã",
    "clans.joinClan": "Entrar num Clã",
    "clans.myClan": "Meu Clã",
    "clans.captain": "Capitão",
    "clans.members": "Membros",
    "clans.form.name": "Nome do Clã",
    "clans.form.sport": "Esporte Principal",
    "clans.form.primaryColor": "Cor Primária",
    "clans.form.secondaryColor": "Cor Secundária",
    "clans.form.desc": "Descrição",
    "clans.btn.create": "Criar Clã",
    "clans.btn.creating": "Criando...",
    "clans.join.title": "Entrar em um Clã",
    "clans.join.desc": "Peça ao capitão o código de convite e insira-o abaixo.",
    "clans.btn.join": "Solicitar Entrada",
    "clans.btn.joining": "Enviando...",
    "clans.inviteCode": "Código de Convite:",
    "clans.errorDuplicateName": "Já existe um clã com esse nome",
    "clans.errorCreate": "Erro ao criar clã",
    "clans.errorInvalidCode": "Código inválido",
    "clans.errorAlreadyRequested": "Você já enviou uma solicitação para este clã",
    "clans.successJoinRequest": "Solicitação enviada ao capitão do clã",
    "clans.errorJoin": "Erro ao entrar no clã",
    "clans.successFriendAdded": "Amigo adicionado ao clã",
    "clans.errorAlreadyMember": "Já é membro deste clã",
    "clans.errorAddFriend": "Erro ao adicionar amigo",
    "clans.successUpdated": "Clã atualizado",
    "clans.errorEdit": "Erro ao editar clã",
    "clans.confirmRemoveMember": "Tem certeza que deseja remover este membro do clã?",
    "clans.errorRemoveMember": "Erro ao remover membro",
    "clans.confirmLeave": "Tem certeza que deseja sair deste clã?",
    "clans.errorLeave": "Erro ao sair do clã",
    "clans.noClansAvailable": "Nenhum clã disponível",
    "common.back": "Voltar",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.success": "Sucesso!",
    "common.search": "Buscar...",
    "common.noResults": "Sem resultados",
    "common.years": "anos",
  },
  fr: {
    "settings.title": "Paramètres",
    "settings.aesthetics": "Esthétique",
    "settings.language": "Langue",
    "settings.gamePrefs": "Préférences de Jeu",
    "settings.rpgMode": "Mode RPG Actif",
    "settings.rpgModeDesc": "Affiche niveaux, XP, coffres et stats.",
    "settings.pushNotif": "Notifications Push",
    "settings.pushNotifDesc": "Alertes de matchs et invitations de clan.",
    "settings.distance": "Unité de Distance",
    "settings.distanceDesc": "Pour trouver des événements à proximité.",
    "settings.logout": "Se Déconnecter",
    "themes.light": "Clair",
    "themes.dark": "Sombre",
    "themes.neon": "Néon",
    "themes.nature": "Nature",
    "themes.ocean": "Océan",
    "nav.events": "Événements",
    "nav.sports": "Sports",
    "nav.map": "Carte",
    "nav.friends": "Amis",
    "nav.profile": "Profil",
    "nav.clans": "Clans",
    "profile.rpgActive": "Mode RPG Actif",
    "profile.level": "Niveau",
    "profile.xpPoints": "Points d'Expérience",
    "profile.achievements": "Succès",
    "profile.progress": "Progrès",
    "profile.stats": "Stats",
    "profile.inventory": "Coffre",
    "profile.history": "Historique",
    "profile.logout": "Déconnexion",
    "profile.editProfile": "Modifier le Profil",
    "profile.organizer": "Organisateur",
    "profile.age": "Âge",
    "profile.gender": "Genre",
    "profile.location": "Emplacement",
    "profile.aboutMe": "À propos de moi",
    "profile.favSports": "Sports Favoris",
    "profile.closeProfile": "Fermer le Profil",
    "profile.male": "Masculin",
    "profile.female": "Féminin",
    "profile.playerAttributes": "Attributs du Joueur",
    "profile.str": "Force (STR)",
    "profile.strDesc": "Augmente en rejoignant des matchs (+2 XP/match)",
    "profile.wis": "Sagesse (WIS)",
    "profile.wisDesc": "Augmente en créant des matchs (+5 XP/match)",
    "profile.con": "Constitution (CON)",
    "profile.conDesc": "Augmente avec l'utilisation quotidienne",
    "profile.cha": "Charisme (CHA)",
    "profile.chaDesc": "Calculé par réputation",
    "profile.profileInfo": "Infos du Profil",
    "profile.favoriteSports": "Sports favoris",
    "profile.campaignSummary": "Résumé de la Campagne",
    "profile.campaignDesc": "Vous avez terminé **{joined} matchs** et créé **{created} événements**. Votre constance vous a accordé **{used} jours d'entraînement**.",
    "profile.classRecruit": "Recrue Novice 👟",
    "profile.classAspirant": "Aspirant Actif ⚡",
    "profile.classWarrior": "Guerrier Fitness 🏋️‍♂️",
    "profile.classMaster": "Maître du Match 🏆",
    "profile.classLegend": "Légende de Caracas 🌟",
    "profile.rarityNovice": "Novice",
    "profile.rarityCommon": "Commun",
    "profile.rarityRare": "Rare",
    "profile.rarityEpic": "Épique",
    "profile.rarityLegendary": "Légendaire",
    "profile.achievementsListTitle": "Liste des Succès",
    "profile.active": "Actifs",
    "profile.adventureLog": "Journal d'Aventure (XP Log)",
    "profile.bronze": "Bronze 🥉",
    "profile.code": "Code :",
    "profile.createFreeAccount": "Créer un Compte Gratuit",
    "profile.emptyChest": "Coffre Vide",
    "profile.emptyChestDesc": "Vous n'avez pas de coupons. Organisez des événements (+25 XP) ou rejoignez des matchs (+15 XP) pour gagner des coffres !",
    "profile.epicItem": "Objet Épique 🟣",
    "profile.eventsPerMonth": "Événements/mois",
    "profile.gold": "Or 🥇",
    "profile.guestDesc": "Explorez librement. Créez un compte pour tout débloquer.",
    "profile.guestDisclaimer": "Votre compte est 100% gratuit.",
    "profile.guestTitle": "Profil Invité",
    "profile.itemClaimed": "Objet Réclamé ! 🎉",
    "profile.itemClaimedDesc": "L'avantage **{discount}** a été activé.",
    "profile.joinCommunity": "Rejoignez la communauté",
    "profile.joinDesc": "Accédez à tout gratuitement",
    "profile.legendaryItem": "Objet Légendaire 🟡",
    "profile.locked": "Verrouillé",
    "profile.loginExisting": "J'ai déjà un compte - Connexion",
    "profile.magicChest": "Coffre Magique",
    "profile.noXp": "Pas encore d'expérience.",
    "profile.platinum": "Platine 💎",
    "profile.players": "Joueurs",
    "profile.rating": "Évaluation",
    "profile.silver": "Argent 🥈",
    "profile.unlocked": "Débloqué",
    "profile.xpForNextLevel": "+{xp} XP pour le Niveau {level}",
    "canchas.location": "Emplacement",
    "canchas.locationSelected": "Emplacement sélectionné",
    "createEvent.intensity.principiante": "Débutant",
    "createEvent.intensity.intermedio": "Intermédiaire",
    "createEvent.intensity.pro": "Pro",
    "events.joinEvent": "Rejoindre le Match",
    "events.createEvent": "Créer un Événement",
    "events.noEvents": "Aucun événement disponible",
    "events.search": "Rechercher...",
    "events.participants": "Participants",
    "events.registerClan": "Inscrire mon Clan",
    "clans.title": "Clans",
    "clans.createClan": "Créer un Clan",
    "clans.joinClan": "Rejoindre un Clan",
    "clans.myClan": "Mon Clan",
    "clans.captain": "Capitaine",
    "clans.members": "Membres",
    "clans.errorDuplicateName": "Un clan avec ce nom existe déjà",
    "clans.errorCreate": "Erreur lors de la création du clan",
    "clans.errorInvalidCode": "Code invalide",
    "clans.errorAlreadyRequested": "Vous avez déjà envoyé une demande à ce clan",
    "clans.successJoinRequest": "Demande envoyée au capitaine du clan",
    "clans.errorJoin": "Erreur lors de la jonction au clan",
    "clans.successFriendAdded": "Ami ajouté au clan",
    "clans.errorAlreadyMember": "Déjà membre de ce clan",
    "clans.errorAddFriend": "Erreur lors de l'ajout d'un ami",
    "clans.successUpdated": "Clan mis à jour",
    "clans.errorEdit": "Erreur lors de la modification du clan",
    "clans.confirmRemoveMember": "Êtes-vous sûr de vouloir retirer ce membre du clan ?",
    "clans.errorRemoveMember": "Erreur lors de la suppression du membre",
    "clans.confirmLeave": "Êtes-vous sûr de vouloir quitter ce clan ?",
    "clans.errorLeave": "Erreur en quittant le clan",
    "clans.noClansAvailable": "Aucun clan disponible",
    "common.back": "Retour",
    "common.save": "Sauvegarder",
    "common.cancel": "Annuler",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès !",
    "common.search": "Rechercher...",
    "common.noResults": "Aucun résultat",
    "common.years": "ans",
  },
  it: {
    "settings.title": "Impostazioni",
    "settings.aesthetics": "Estetica dell'App",
    "settings.language": "Lingua",
    "settings.gamePrefs": "Preferenze di Gioco",
    "settings.rpgMode": "Modalità RPG Attiva",
    "settings.rpgModeDesc": "Mostra livelli, XP, forzieri e statistiche.",
    "settings.pushNotif": "Notifiche Push",
    "settings.pushNotifDesc": "Avvisi di partite e inviti ai clan.",
    "settings.distance": "Unità di Distanza",
    "settings.distanceDesc": "Per trovare eventi vicini.",
    "settings.logout": "Esci",
    "themes.light": "Chiaro",
    "themes.dark": "Scuro",
    "themes.neon": "Neon",
    "themes.nature": "Natura",
    "themes.ocean": "Oceano",
    "nav.events": "Eventi",
    "nav.sports": "Sport",
    "nav.map": "Mappa",
    "nav.friends": "Amici",
    "nav.profile": "Profilo",
    "nav.clans": "Clan",
    "profile.rpgActive": "Modalità RPG Attiva",
    "profile.level": "Livello",
    "profile.xpPoints": "Punti Esperienza",
    "profile.achievements": "Obiettivi",
    "profile.progress": "Progresso",
    "profile.stats": "Stats",
    "profile.inventory": "Forziere",
    "profile.history": "Cronologia",
    "profile.logout": "Esci",
    "profile.editProfile": "Modifica Profilo",
    "profile.organizer": "Organizzatore",
    "profile.age": "Età",
    "profile.gender": "Genere",
    "profile.location": "Posizione",
    "profile.aboutMe": "Su di me",
    "profile.favSports": "Sport Preferiti",
    "profile.closeProfile": "Chiudi Profilo",
    "profile.male": "Maschile",
    "profile.female": "Femminile",
    "profile.playerAttributes": "Attributi del Giocatore",
    "profile.str": "Forza (STR)",
    "profile.strDesc": "Aumenta unendosi alle partite (+2 XP/partita)",
    "profile.wis": "Saggezza (WIS)",
    "profile.wisDesc": "Aumenta creando partite (+5 XP/partita)",
    "profile.con": "Costituzione (CON)",
    "profile.conDesc": "Aumenta con l'uso quotidiano",
    "profile.cha": "Carisma (CHA)",
    "profile.chaDesc": "Calcolato sulla reputazione",
    "profile.profileInfo": "Info Profilo",
    "profile.favoriteSports": "Sport preferiti",
    "profile.campaignSummary": "Riepilogo Campagna",
    "profile.campaignDesc": "Hai completato **{joined} partite** e creato **{created} eventi**. La tua costanza ti ha garantito **{used} giorni di allenamento**.",
    "profile.classRecruit": "Recluta Novellino 👟",
    "profile.classAspirant": "Aspirante Attivo ⚡",
    "profile.classWarrior": "Guerriero Fitness 🏋️‍♂️",
    "profile.classMaster": "Maestro del Match 🏆",
    "profile.classLegend": "Leggenda di Caracas 🌟",
    "profile.rarityNovice": "Novellino",
    "profile.rarityCommon": "Comune",
    "profile.rarityRare": "Raro",
    "profile.rarityEpic": "Epico",
    "profile.rarityLegendary": "Leggendario",
    "profile.achievementsListTitle": "Lista degli Obiettivi",
    "profile.active": "Attivi",
    "profile.adventureLog": "Diario delle Avventure (XP Log)",
    "profile.bronze": "Bronzo 🥉",
    "profile.code": "Codice:",
    "profile.createFreeAccount": "Crea Account Gratuito",
    "profile.emptyChest": "Forziere Vuoto",
    "profile.emptyChestDesc": "Non hai coupon. Organizza eventi (+25 XP) o unisciti a partite (+15 XP) per guadagnare forzieri!",
    "profile.epicItem": "Oggetto Epico 🟣",
    "profile.eventsPerMonth": "Eventi/mese",
    "profile.gold": "Oro 🥇",
    "profile.guestDesc": "Esplora liberamente. Crea un account per sbloccare tutto.",
    "profile.guestDisclaimer": "Il tuo account è gratuito al 100%.",
    "profile.guestTitle": "Profilo Ospite",
    "profile.itemClaimed": "Oggetto Riscattato! 🎉",
    "profile.itemClaimedDesc": "Il vantaggio **{discount}** è stato attivato.",
    "profile.joinCommunity": "Unisciti alla comunità",
    "profile.joinDesc": "Accedi a tutto gratis",
    "profile.legendaryItem": "Oggetto Leggendario 🟡",
    "profile.locked": "Bloccato",
    "profile.loginExisting": "Ho già un account - Accedi",
    "profile.magicChest": "Forziere Magico",
    "profile.noXp": "Ancora nessuna esperienza.",
    "profile.platinum": "Platino 💎",
    "profile.players": "Giocatori",
    "profile.rating": "Valutazione",
    "profile.silver": "Argento 🥈",
    "profile.unlocked": "Sbloccato",
    "profile.xpForNextLevel": "+{xp} XP per il Livello {level}",
    "canchas.location": "Posizione",
    "canchas.locationSelected": "Posizione selezionata",
    "createEvent.intensity.principiante": "Principiante",
    "createEvent.intensity.intermedio": "Intermedio",
    "createEvent.intensity.pro": "Pro",
    "events.joinEvent": "Unisciti alla Partita",
    "events.createEvent": "Crea Evento",
    "events.noEvents": "Nessun evento disponibile",
    "events.search": "Cerca eventi...",
    "events.participants": "Partecipanti",
    "events.registerClan": "Iscrivere il mio Clan",
    "clans.title": "Clan",
    "clans.createClan": "Crea Clan",
    "clans.joinClan": "Unisciti a un Clan",
    "clans.myClan": "Il mio Clan",
    "clans.captain": "Capitano",
    "clans.members": "Membri",
    "clans.errorDuplicateName": "Un clan con questo nome esiste già",
    "clans.errorCreate": "Errore durante la creazione del clan",
    "clans.errorInvalidCode": "Codice non valido",
    "clans.errorAlreadyRequested": "Hai già inviato una richiesta a questo clan",
    "clans.successJoinRequest": "Richiesta inviata al capitano del clan",
    "clans.errorJoin": "Errore durante l'adesione al clan",
    "clans.successFriendAdded": "Amico aggiunto al clan",
    "clans.errorAlreadyMember": "Già membro di questo clan",
    "clans.errorAddFriend": "Errore durante l'aggiunta dell'amico",
    "clans.successUpdated": "Clan aggiornato",
    "clans.errorEdit": "Errore durante la modifica del clan",
    "clans.confirmRemoveMember": "Sei sicuro di voler rimuovere questo membro dal clan?",
    "clans.errorRemoveMember": "Errore durante la rimozione del membro",
    "clans.confirmLeave": "Sei sicuro di voler lasciare questo clan?",
    "clans.errorLeave": "Errore nell'abbandono del clan",
    "clans.noClansAvailable": "Nessun clan disponibile",
    "common.back": "Indietro",
    "common.save": "Salva",
    "common.cancel": "Annulla",
    "common.loading": "Caricamento...",
    "common.error": "Errore",
    "common.success": "Successo!",
    "common.search": "Cerca...",
    "common.noResults": "Nessun risultato",
    "common.years": "anni",
  },
  de: {
    "settings.title": "Einstellungen",
    "settings.aesthetics": "App-Ästhetik",
    "settings.language": "Sprache",
    "settings.gamePrefs": "Spieleinstellungen",
    "settings.rpgMode": "RPG-Modus Aktiv",
    "settings.rpgModeDesc": "Zeigt Level, XP, Truhen und Stats an.",
    "settings.pushNotif": "Push-Benachrichtigungen",
    "settings.pushNotifDesc": "Spielbenachrichtigungen und Clan-Einladungen.",
    "settings.distance": "Entfernungseinheit",
    "settings.distanceDesc": "Um Ereignisse in der Nähe zu finden.",
    "settings.logout": "Abmelden",
    "themes.light": "Hell",
    "themes.dark": "Dunkel",
    "themes.neon": "Neon",
    "themes.nature": "Natur",
    "themes.ocean": "Ozean",
    "nav.events": "Ereignisse",
    "nav.sports": "Sport",
    "nav.map": "Karte",
    "nav.friends": "Freunde",
    "nav.profile": "Profil",
    "nav.clans": "Clans",
    "profile.rpgActive": "RPG-Modus Aktiv",
    "profile.level": "Level",
    "profile.xpPoints": "Erfahrungspunkte",
    "profile.achievements": "Erfolge",
    "profile.progress": "Fortschritt",
    "profile.stats": "Stats",
    "profile.inventory": "Truhe",
    "profile.history": "Verlauf",
    "profile.logout": "Abmelden",
    "profile.editProfile": "Profil Bearbeiten",
    "profile.organizer": "Organisator",
    "profile.age": "Alter",
    "profile.gender": "Geschlecht",
    "profile.location": "Ort",
    "profile.aboutMe": "Über mich",
    "profile.favSports": "Lieblingssportarten",
    "profile.closeProfile": "Profil schließen",
    "profile.male": "Männlich",
    "profile.female": "Weiblich",
    "profile.playerAttributes": "Spielerattribute",
    "profile.str": "Stärke (STR)",
    "profile.strDesc": "Steigt beim Beitreten zu Spielen (+2 XP/Spiel)",
    "profile.wis": "Weisheit (WIS)",
    "profile.wisDesc": "Steigt beim Erstellen von Spielen (+5 XP/Spiel)",
    "profile.con": "Konstitution (CON)",
    "profile.conDesc": "Steigt bei täglicher Nutzung",
    "profile.cha": "Charisma (CHA)",
    "profile.chaDesc": "Basierend auf dem Ruf berechnet",
    "profile.profileInfo": "Profilinfo",
    "profile.favoriteSports": "Lieblingssport",
    "profile.campaignSummary": "Kampagnenzusammenfassung",
    "profile.campaignDesc": "Sie haben **{joined} Spiele** abgeschlossen und **{created} Events** erstellt. Ihre Beständigkeit hat Ihnen **{used} Trainingstage** eingebracht.",
    "profile.classRecruit": "Rekrut Anfänger 👟",
    "profile.classAspirant": "Aktiver Anwärter ⚡",
    "profile.classWarrior": "Fitness Krieger 🏋️‍♂️",
    "profile.classMaster": "Match-Meister 🏆",
    "profile.classLegend": "Legende von Caracas 🌟",
    "profile.rarityNovice": "Anfänger",
    "profile.rarityCommon": "Gewöhnlich",
    "profile.rarityRare": "Selten",
    "profile.rarityEpic": "Episch",
    "profile.rarityLegendary": "Legendär",
    "profile.achievementsListTitle": "Erfolgsliste",
    "profile.active": "Aktiv",
    "profile.adventureLog": "Abenteuer-Logbuch (XP Log)",
    "profile.bronze": "Bronze 🥉",
    "profile.code": "Code:",
    "profile.createFreeAccount": "Kostenloses Konto erstellen",
    "profile.emptyChest": "Leere Truhe",
    "profile.emptyChestDesc": "Sie haben keine Gutscheine. Organisieren Sie Events (+25 XP) oder nehmen Sie an Spielen teil (+15 XP), um Truhen zu verdienen!",
    "profile.epicItem": "Epischer Gegenstand 🟣",
    "profile.eventsPerMonth": "Events/Monat",
    "profile.gold": "Gold 🥇",
    "profile.guestDesc": "Frei erkunden. Konto erstellen, um alles freizuschalten.",
    "profile.guestDisclaimer": "Ihr Konto ist 100% kostenlos.",
    "profile.guestTitle": "Gastprofil",
    "profile.itemClaimed": "Gegenstand beansprucht! 🎉",
    "profile.itemClaimedDesc": "Der Vorteil **{discount}** wurde aktiviert.",
    "profile.joinCommunity": "Tritt der Community bei",
    "profile.joinDesc": "Kostenloser Zugriff auf alles",
    "profile.legendaryItem": "Legendärer Gegenstand 🟡",
    "profile.locked": "Gesperrt",
    "profile.loginExisting": "Ich habe bereits ein Konto - Anmelden",
    "profile.magicChest": "Magische Truhe",
    "profile.noXp": "Noch keine Erfahrung.",
    "profile.platinum": "Platin 💎",
    "profile.players": "Spieler",
    "profile.rating": "Bewertung",
    "profile.silver": "Silber 🥈",
    "profile.unlocked": "Freigeschaltet",
    "profile.xpForNextLevel": "+{xp} XP für Level {level}",
    "canchas.location": "Ort",
    "canchas.locationSelected": "Ort ausgewählt",
    "createEvent.intensity.principiante": "Anfänger",
    "createEvent.intensity.intermedio": "Mittelstufe",
    "createEvent.intensity.pro": "Profi",
    "events.joinEvent": "Spiel beitreten",
    "events.createEvent": "Ereignis erstellen",
    "events.noEvents": "Keine Ereignisse verfügbar",
    "events.search": "Suche...",
    "events.participants": "Teilnehmer",
    "events.registerClan": "Meinen Clan anmelden",
    "clans.title": "Clans",
    "clans.createClan": "Clan erstellen",
    "clans.joinClan": "Clan beitreten",
    "clans.myClan": "Mein Clan",
    "clans.captain": "Kapitän",
    "clans.members": "Mitglieder",
    "clans.errorDuplicateName": "Ein Clan mit diesem Namen existiert bereits",
    "clans.errorCreate": "Fehler beim Erstellen des Clans",
    "clans.errorInvalidCode": "Ungültiger Code",
    "clans.errorAlreadyRequested": "Sie haben bereits eine Anfrage an diesen Clan gesendet",
    "clans.successJoinRequest": "Anfrage an den Clan-Kapitän gesendet",
    "clans.errorJoin": "Fehler beim Beitritt zum Clan",
    "clans.successFriendAdded": "Freund zum Clan hinzugefügt",
    "clans.errorAlreadyMember": "Bereits Mitglied dieses Clans",
    "clans.errorAddFriend": "Fehler beim Hinzufügen des Freundes",
    "clans.successUpdated": "Clan aktualisiert",
    "clans.errorEdit": "Fehler beim Bearbeiten des Clans",
    "clans.confirmRemoveMember": "Sind Sie sicher, dass Sie dieses Mitglied aus dem Clan entfernen möchten?",
    "clans.errorRemoveMember": "Fehler beim Entfernen des Mitglieds",
    "clans.confirmLeave": "Sind Sie sicher, dass Sie diesen Clan verlassen möchten?",
    "clans.errorLeave": "Fehler beim Verlassen des Clans",
    "clans.noClansAvailable": "Keine Clans verfügbar",
    "common.back": "Zurück",
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.loading": "Laden...",
    "common.error": "Fehler",
    "common.success": "Erfolg!",
    "common.search": "Suchen...",
    "common.noResults": "Keine Ergebnisse",
    "common.years": "Jahre",
  },
};

const SettingsContext = createContext<SettingsContextValue>({
  language: "es",
  setLanguage: () => { },
  theme: "light",
  setTheme: () => { },
  rpgMode: true,
  setRpgMode: () => { },
  notifications: true,
  setNotifications: () => { },
  unit: "km",
  setUnit: () => { },
  t: (key) => key,
});

export function SettingsProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("es");
  const [theme, setThemeState] = useState<Theme>("light");
  const [rpgMode, setRpgModeState] = useState(true);
  const [notifications, setNotificationsState] = useState(true);
  const [unit, setUnitState] = useState<"km" | "mi">("km");

  // Load from localStorage on mount
  useEffect(() => {
    const savedLang = localStorage.getItem("app-language") as Language;
    if (savedLang && translations[savedLang]) setLanguageState(savedLang);

    const savedTheme = localStorage.getItem("app-theme") as Theme;
    if (savedTheme) setThemeState(savedTheme);

    const savedRpg = localStorage.getItem("app-rpg");
    if (savedRpg !== null) setRpgModeState(savedRpg !== "false");

    const savedNotif = localStorage.getItem("app-notifications");
    if (savedNotif !== null) setNotificationsState(savedNotif !== "false");

    const savedUnit = localStorage.getItem("app-unit") as "km" | "mi";
    if (savedUnit) setUnitState(savedUnit);
  }, []);

  // Apply theme to <html>
  useEffect(() => {
    const html = document.documentElement;
    html.classList.remove("dark", "theme-neon", "theme-nature", "theme-ocean");
    if (theme === "dark") html.classList.add("dark");
    else if (theme !== "light") html.classList.add(`theme-${theme}`);
    localStorage.setItem("app-theme", theme);
  }, [theme]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const setTheme = (t: Theme) => {
    setThemeState(t);
  };

  const setRpgMode = (val: boolean) => {
    setRpgModeState(val);
    localStorage.setItem("app-rpg", val.toString());
  };

  const setNotifications = (val: boolean) => {
    setNotificationsState(val);
    localStorage.setItem("app-notifications", val.toString());
  };

  const setUnit = (val: "km" | "mi") => {
    setUnitState(val);
    localStorage.setItem("app-unit", val);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] ?? translations["es"][key] ?? key;
  };

  return (
    <SettingsContext.Provider value={{ language, setLanguage, theme, setTheme, rpgMode, setRpgMode, notifications, setNotifications, unit, setUnit, t }}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings() {
  return useContext(SettingsContext);
}
