export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string; // Emoji
  rarity: "bronze" | "silver" | "gold" | "platinum";
  xpReward: number;
}

export const ACHIEVEMENTS: Achievement[] = [
  // BRONZE (12 achievements, 15 XP)
  {
    id: "primer_paso",
    title: "Primer Paso",
    description: "Inscríbete y participa en tu primer partido",
    icon: "👟",
    rarity: "bronze",
    xpReward: 15,
  },
  {
    id: "gran_carisma",
    title: "Alma de la Pista",
    description: "Consigue al menos 3 puntos de carisma",
    icon: "🤝",
    rarity: "bronze",
    xpReward: 15,
  },
  {
    id: "iniciado_uso",
    title: "Entrenamiento Diario",
    description: "Usa la aplicación durante 2 días",
    icon: "🏃‍♂️",
    rarity: "bronze",
    xpReward: 15,
  },
  {
    id: "organizador_novato",
    title: "Organizador Novato",
    description: "Crea tu segundo partido en la plataforma",
    icon: "📢",
    rarity: "bronze",
    xpReward: 15,
  },
  {
    id: "primer_contacto",
    title: "Primer Contacto",
    description: "Consigue tu primer punto de carisma",
    icon: "💬",
    rarity: "bronze",
    xpReward: 15,
  },
  {
    id: "primer_nivel",
    title: "Paso Firme",
    description: "Alcanza el Nivel 2 de experiencia",
    icon: "🌱",
    rarity: "bronze",
    xpReward: 15,
  },
  {
    id: "nivel_tres",
    title: "Aspirante Activo",
    description: "Alcanza el Nivel 3 de experiencia",
    icon: "⚡",
    rarity: "bronze",
    xpReward: 15,
  },
  {
    id: "carta_presentacion",
    title: "Carta de Presentación",
    description: "Añade una descripción sobre ti en tu perfil",
    icon: "📝",
    rarity: "bronze",
    xpReward: 15,
  },
  {
    id: "establecido",
    title: "Deportista Local",
    description: "Configura tu ubicación en tu perfil",
    icon: "📍",
    rarity: "bronze",
    xpReward: 15,
  },
  {
    id: "multidisciplinario",
    title: "Multidisciplinario",
    description: "Selecciona al menos 3 deportes preferidos en tu perfil",
    icon: "🎾",
    rarity: "bronze",
    xpReward: 15,
  },
  {
    id: "primer_ahorro",
    title: "Ahorrador RPG",
    description: "Canjea tu primer cupón en el cofre",
    icon: "💎",
    rarity: "bronze",
    xpReward: 15,
  },
  {
    id: "espiritu_comunidad",
    title: "Espíritu de Comunidad",
    description: "Acepta a tu primer amigo",
    icon: "👋",
    rarity: "bronze",
    xpReward: 15,
  },

  // SILVER (9 achievements, 25 XP)
  {
    id: "creador_leyendas",
    title: "Creador de Leyendas",
    description: "Crea y organiza tu primer evento deportivo",
    icon: "⚽",
    rarity: "silver",
    xpReward: 25,
  },
  {
    id: "fidelidad_hierro",
    title: "Fidelidad de Hierro",
    description: "Registra 5 días de entrenamiento abriendo la app",
    icon: "📅",
    rarity: "silver",
    xpReward: 25,
  },
  {
    id: "habito_saludable",
    title: "Hábito Saludable",
    description: "Usa la aplicación durante 10 días",
    icon: "🍎",
    rarity: "silver",
    xpReward: 25,
  },
  {
    id: "miembro_equipo",
    title: "Miembro del Equipo",
    description: "Participa en 5 partidos en total",
    icon: "👕",
    rarity: "silver",
    xpReward: 25,
  },
  {
    id: "popular",
    title: "Popular",
    description: "Consigue 5 puntos de carisma",
    icon: "🌟",
    rarity: "silver",
    xpReward: 25,
  },
  {
    id: "maestro_match",
    title: "Maestro del Match",
    description: "Alcanza el Nivel 4 de experiencia",
    icon: "🎓",
    rarity: "silver",
    xpReward: 25,
  },
  {
    id: "perfil_completo",
    title: "Identidad Revelada",
    description: "Completa todos los campos básicos de tu perfil (nombre, edad, género, descripción y ubicación)",
    icon: "🛡️",
    rarity: "silver",
    xpReward: 25,
  },
  {
    id: "coleccionista_cupones",
    title: "Acumulador de Pergaminos",
    description: "Consigue al menos 3 cupones en tu inventario",
    icon: "📜",
    rarity: "silver",
    xpReward: 25,
  },
  {
    id: "favorito_casa",
    title: "Favorito de la Casa",
    description: "Participa en tres partidos en una misma ubicación",
    icon: "🏠",
    rarity: "silver",
    xpReward: 25,
  },

  // GOLD (10 achievements, 50 XP)
  {
    id: "viajero_deporte",
    title: "Deportista Consagrado",
    description: "Participa activamente en 3 partidos",
    icon: "🏆",
    rarity: "gold",
    xpReward: 50,
  },
  {
    id: "nivel_heroe",
    title: "Leyenda de Caracas",
    description: "Alcanza el Nivel 5 de experiencia",
    icon: "👑",
    rarity: "gold",
    xpReward: 50,
  },
  {
    id: "atleta_constante",
    title: "Atleta Constante",
    description: "Usa la aplicación durante 20 días",
    icon: "🔥",
    rarity: "gold",
    xpReward: 50,
  },
  {
    id: "imparable",
    title: "Imparable",
    description: "Usa la aplicación durante 50 días",
    icon: "♾️",
    rarity: "gold",
    xpReward: 50,
  },
  {
    id: "veterano_canchas",
    title: "Veterano de las Canchas",
    description: "Participa en 10 partidos en total",
    icon: "🏟️",
    rarity: "gold",
    xpReward: 50,
  },
  {
    id: "estrella_liga",
    title: "Estrella de la Liga",
    description: "Participa en 20 partidos en total",
    icon: "🌠",
    rarity: "gold",
    xpReward: 50,
  },
  {
    id: "lider_grupo",
    title: "Líder de Grupo",
    description: "Crea 5 partidos en la plataforma",
    icon: "📢",
    rarity: "gold",
    xpReward: 50,
  },
  {
    id: "director_tecnico",
    title: "Director Técnico",
    description: "Crea 10 partidos en la plataforma",
    icon: "📋",
    rarity: "gold",
    xpReward: 50,
  },
  {
    id: "idolo_masas",
    title: "Ídolo de Masas",
    description: "Consigue 10 puntos de carisma",
    icon: "🤩",
    rarity: "gold",
    xpReward: 50,
  },
  {
    id: "semidios_deporte",
    title: "Semidiós del Deporte",
    description: "Alcanza el Nivel 10 de experiencia",
    icon: "🔱",
    rarity: "gold",
    xpReward: 50,
  },

  // PLATINUM (1 achievement, 100 XP)
  {
    id: "maestro_teammatch",
    title: "Coleccionista de Trofeos",
    description: "Consigue todos los demás logros de la aplicación",
    icon: "🌌",
    rarity: "platinum",
    xpReward: 100,
  },
];
