import running from "@/assets/running-trail.jpg";
import hiking from "@/assets/hiking-trail.jpg";
import padel from "@/assets/padel-court.jpg";
import type { SportEvent } from "./types";

export const events: SportEvent[] = [
  {
    id: "1",
    title: "Running grupal en Chacao",
    sport: "Running",
    level: "Intermedio",
    location: "Parque El Bosque",
    zone: "Chacao",
    date: "Hoy",
    time: "18:00 – 19:30",
    price: 8,
    spots: 14,
    joined: 11,
    host: "Diego R.",
    hostAvatar: "DR",
    image: running,
    distanceKm: 1.2,
    lat: 10.4939,
    lng: -66.8522,
  },
  {
    id: "2",
    title: "Senderismo al Ávila",
    sport: "Senderismo",
    level: "Avanzado",
    location: "Sabas Nieves",
    zone: "Altamira",
    date: "Hoy",
    time: "06:00 – 09:00",
    price: 0,
    spots: 10,
    joined: 6,
    host: "Andrea M.",
    hostAvatar: "AM",
    image: hiking,
    distanceKm: 2.4,
    lat: 10.5100,
    lng: -66.8500,
  },
  {
    id: "3",
    title: "Pádel mixto nivel medio",
    sport: "Pádel",
    level: "Intermedio",
    location: "Padel Club Las Mercedes",
    zone: "Las Mercedes",
    date: "Mañana",
    time: "07:00 – 08:30",
    price: 12,
    spots: 4,
    joined: 3,
    host: "Carlos P.",
    hostAvatar: "CP",
    image: padel,
    distanceKm: 3.1,
    lat: 10.4815,
    lng: -66.8615,
  },
  {
    id: "4",
    title: "Vóleibol playa",
    sport: "Vóleibol",
    level: "Principiante",
    location: "Parque Los Caobos",
    zone: "Los Caobos",
    date: "Sáb 10",
    time: "16:00 – 18:00",
    price: 5,
    spots: 12,
    joined: 4,
    host: "María L.",
    hostAvatar: "ML",
    image: running,
    distanceKm: 4.8,
    lat: 10.4988,
    lng: -66.8967,
  },
];
